"""add tags table

Revision ID: d6e27c6cda37
Revises: 578472d6ca99
Create Date: 2025-02-06 23:05:10.973005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e27c6cda37'
down_revision: Union[str, None] = '578472d6ca99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('booktag',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.uid'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'updated_at')
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'update_at')
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'update_at')
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'update_at')
    op.drop_table('booktag')
    op.drop_table('tags')
    # ### end Alembic commands ###
